nc_vote/nc_vote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('vote/', include('vote.urls')),
    path('admin/', admin.site.urls),
]

nc_vote/vote/urls.py
from django.urls import path
from . import views

app_name = 'vote'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:district_num>/ballot', views.ballot, name="ballot"),
    path('finished', views.tally, name="tally"),
    path('votetotals', views.votetotals, name="votetotals")
]

nc_vote/vote/models.py
from django.db import models

# Create your models here.


class District(models.Model):
    district_num = models.IntegerField(default=0)

    def __str__(self):
        return "District " + str(self.district_num)


class BallotText(models.Model):
    ballot_text = models.CharField(max_length=120)
    district_num = models.IntegerField(default=0)
    ballot_cat = models.IntegerField(default=0)

    def __str__(self):
        return self.ballot_text


class Candidate(models.Model):
    candidate = models.ForeignKey(BallotText, on_delete=models.CASCADE)
    candidate_text = models.CharField(max_length=120)
    votes = models.IntegerField(default=0)
    district_num = models.IntegerField(default=0)
    ballot_cat = models.IntegerField(default=0)

    def __str__(self):
        return self.candidate_text

nc_vote/vote/forms.py
from django import forms


class VoteForm(forms.Form):

    name = forms.CharField()

nc_vote/vote/views.py
from django.shortcuts import render

# Create your views here.
from .models import BallotText, Candidate, District


def index(request):
    districts = District.objects.all
    context = {'districts': districts}
    return render(request, 'vote/index.html', context)


def ballot(request, district_num):
    ballot_list = BallotText.objects.all
    context = {'ballot_list': ballot_list}
    return render(request, 'vote/'+str(district_num)+'/ballot.html', context)


def votetotals(request):
    candidates = Candidate.objects.all
    return render(request, 'vote/votetotals.html', {"candidates": candidates})

def tally(request):

    if request.method == "POST":
        list = request.POST
        candidates_id = list.items()
        all_candidates = Candidate.objects.all()
        for id in candidates_id:
            print(id[1])
            for candidate in all_candidates:
                print(candidate.candidate_text)
                if candidate.candidate_text == id[1]:
                    print(candidate.candidate_text + " " + id[1])
                    candidate.votes += 1
                    candidate.save()
        return render(request, 'vote/votetotals.html')
    else:
        return render(request, 'vote/votetotals.html')

nc_vote/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <title>NC VOTES {% block title %} {% endblock %}</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 m-auto">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

nc_vote/templates/statewide.html
{% extends 'base.html' %}
{% block content %}
    {% block title %}
        <h1 class="text-center mb-3">Ballot</h1>
    {% endblock %}
    {% block customcontent %}
    {% endblock %}
{% endblock %}

nc_vote/templates/vote/11/ballot.html
{% extends 'statewide.html' %}
{% block customcontent %}

    <form action="{% url 'vote:tally' %}" method="post">
    {% csrf_token %}
    {% for ballot in ballot_list %}

        <label class="text-center mb-3">{{ballot.ballot_text}}</label>
        </br>
        <div class="form-check">
        {% for candidate in ballot.candidate_set.all %}
            {% if candidate.district_num == 11 or candidate.district_num == 0 %}
                <input
                    type="radio"
                    class="form-check-input"
                    name="{{ballot.ballot_text}}"
                    value="{{candidate.candidate_text}}"
                >
                <label>{{candidate.candidate_text}}</label>
            </br>
            {% endif %}


        {% endfor %}
        </br>
        </div>
    {% endfor %}

            <input

                    type="submit"
                    value="Cast Your Vote"
                    class="btn btn-success"
            />

    </form>

    </form>
{% endblock %}

nc_vote/templates/vote/6/ballot.html
{% extends 'statewide.html' %}
{% block customcontent %}

    <form action="{% url 'vote:tally' %}" method="post">
    {% csrf_token %}
    {% for ballot in ballot_list %}

        <label class="text-center mb-3">{{ballot.ballot_text}}</label>
        </br>
        <div class="form-check">
        {% for candidate in ballot.candidate_set.all %}
            {% if candidate.district_num == 6 or candidate.district_num == 0 %}
                <input
                    type="radio"
                    class="form-check-input"
                    name="{{ballot.ballot_text}}"
                    value="{{candidate.candidate_text}}"
                >
                <label>{{candidate.candidate_text}}</label>
            </br>
            {% endif %}


        {% endfor %}
        </br>
        </div>
    {% endfor %}

            <input

                    type="submit"
                    value="Cast Your Vote"
                    class="btn btn-success"
            />

    </form>

    </form>
{% endblock %}

nc_vote/templates/vote/finished.html
{% extends 'base.html' %}
{% block content %}
<h1>Thank you</h1>
{% endblock %}

nc_vote/templates/vote/index.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center mb-3">Choose Ballot</h1>
    {% if districts %}
    {% for district in districts %}
    <a href="/vote/{{district.district_num}}/ballot">
        <div class="card mb-3">
            <div class="card-body">
                <p class="lead">District {{district.district_num}}</p>
            </div>
        </div>
    </a>
    {% endfor %}
    {% else %}
    <p>No data available</p>
    {% endif %}
{% endblock %}

nc_vote/templates/vote/votetotals.html
{% extends 'base.html' %}
{% block content %}
<h1>Vote Totals</h1>
{% for candidate in candidates %}
    <h2>{{candidate.candidate_text}} {{candidate.votes}}</h2>
{% endfor %}
{% endblock %}